const db=window.PF_SUPABASE;const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];const state={user:null,projects:[],services:[]};
const ADMIN_NAME_HASH='1b0774cf41a44c5581377f92146efc34ebfc6ccf6a5e78c2ed5656d41bef0a04';
const ADMIN_CREDENTIALS_HASH='a1834cde554f4e4a79145fd3bcbedb034bcdc61e322c2a3606064633f0e8d0cb';
const loginView=$('#loginView'),appView=$('#appView'),loginForm=$('#loginForm'),loginStatus=$('#loginStatus');
function msg(el,text,good=false){if(el){el.textContent=text;el.className='form-status '+(good?'good':'')}}
async function sha256(value){const bytes=new TextEncoder().encode(value);const digest=await crypto.subtle.digest('SHA-256',bytes);return [...new Uint8Array(digest)].map(b=>b.toString(16).padStart(2,'0')).join('')}
async function isAdmin(){if(!state.user)return false;const {data,error}=await db.from('admin_users').select('user_id').eq('user_id',state.user.id).maybeSingle();return !error&&!!data}
function showLogin(){loginView.hidden=false;appView.hidden=true}function showApp(){loginView.hidden=true;appView.hidden=false}
async function boot(){showLogin();if(sessionStorage.getItem('pf_admin_ok')!=='1')return;const {data:{session}}=await db.auth.getSession();if(!session){sessionStorage.removeItem('pf_admin_ok');return}state.user=session.user;if(await isAdmin())showApp();else sessionStorage.removeItem('pf_admin_ok');if(appView.hidden===false)await refreshAll()}
loginForm.addEventListener('submit',async e=>{e.preventDefault();msg(loginStatus,'Verificando…');const username=$('#adminName').value.normalize('NFC').trim();const password=$('#adminPassword').value;const nameHash=await sha256(username);const credentialsHash=await sha256(username+'\n'+password);if(nameHash!==ADMIN_NAME_HASH||credentialsHash!==ADMIN_CREDENTIALS_HASH){msg(loginStatus,'Nombre de administrador o contraseña incorrectos.');return}const {data:{session},error:sessionError}=await db.auth.getSession();if(sessionError||!session){msg(loginStatus,'La cuenta de administración no está autenticada en el sistema. Inicia sesión en Supabase con la cuenta administradora y vuelve a entrar.');return}state.user=session.user;const ok=await isAdmin();if(!ok){msg(loginStatus,'Esta cuenta no tiene permisos de administrador.');return}sessionStorage.setItem('pf_admin_ok','1');$('#adminPassword').value='';showApp();await refreshAll()});
$('#logoutBtn').addEventListener('click',async()=>{sessionStorage.removeItem('pf_admin_ok');location.reload()});
function showPanel(id){$$('.panel').forEach(p=>p.classList.toggle('active-panel',p.id===id));$$('.side-link').forEach(l=>l.classList.toggle('active',l.dataset.panel===id));window.scrollTo({top:0,behavior:'smooth'})}$$('.side-link').forEach(l=>l.addEventListener('click',()=>showPanel(l.dataset.panel)));$$('[data-panel-target]').forEach(b=>b.addEventListener('click',()=>showPanel(b.dataset.panelTarget)));
async function refreshAll(){await Promise.all([loadProjects(),loadServices(),loadRequests()]);updateCounts()}
function updateCounts(){$('#countProjects').textContent=state.projects.length;$('#countServices').textContent=state.services.length;loadPhotoCount()}
async function loadPhotoCount(){const {count}=await db.from('photos').select('*',{count:'exact',head:true});$('#countPhotos').textContent=count||0}
async function loadProjects(){const {data,error}=await db.from('projects').select('*').order('created_at',{ascending:false});if(error){msg($('#projectStatus'),error.message);return}state.projects=data||[];renderProjects();$('#photoProject').innerHTML=state.projects.map(p=>`<option value="${p.id}">${esc(p.name)}</option>`).join('')||'<option value="">Create a project first</option>'}
function renderProjects(){const el=$('#projectList');if(!state.projects.length){el.innerHTML='<div class="empty-table"><div class="empty-icon">00</div><h3>NO PROJECTS</h3><p>Crea el primer proyecto y después sube sus fotografías.</p></div>';return}el.innerHTML=state.projects.map(p=>`<div class="data-row"><div><small>${esc(p.category)} · ${esc(p.location||'')}</small><strong>${esc(p.name)}</strong><span>${esc(p.description||'')}</span></div><div class="row-actions"><button data-edit-project="${p.id}">EDIT</button><button data-delete-project="${p.id}" class="danger">DELETE</button><button data-publish-project="${p.id}">${p.published?'PUBLISHED':'HIDDEN'}</button></div></div>`).join('');$$('[data-edit-project]').forEach(b=>b.onclick=()=>openProject(b.dataset.editProject));$$('[data-delete-project]').forEach(b=>b.onclick=()=>deleteProject(b.dataset.deleteProject));$$('[data-publish-project]').forEach(b=>b.onclick=()=>togglePublish(b.dataset.publishProject))}
$('#newProjectBtn').onclick=()=>openProject();function openProject(id){const p=state.projects.find(x=>x.id===id);$('#projectId').value=p?.id||'';$('#projectName').value=p?.name||'';$('#projectCategory').value=p?.category||'BOXES';$('#projectLocation').value=p?.location||'';$('#projectDate').value=p?.event_date||'';$('#projectDescription').value=p?.description||'';$('#projectPublished').checked=p?.published??true;$('#modalTitle').textContent=p?'EDIT PROJECT.':'NEW PROJECT.';$('#projectStatus').textContent='';$('#projectModal').hidden=false}
$$('[data-close]').forEach(b=>b.onclick=()=>document.getElementById(b.dataset.close).hidden=true);window.addEventListener('keydown',e=>{if(e.key==='Escape'){$$('.modal').forEach(m=>m.hidden=true)}});
$('#projectForm').addEventListener('submit',async e=>{e.preventDefault();const payload={name:$('#projectName').value.trim(),category:$('#projectCategory').value,location:$('#projectLocation').value.trim(),event_date:$('#projectDate').value||null,description:$('#projectDescription').value.trim(),published:$('#projectPublished').checked,updated_at:new Date().toISOString()};const id=$('#projectId').value;const q=id?db.from('projects').update(payload).eq('id',id):db.from('projects').insert(payload).select().single();const {error}=await q;if(error){msg($('#projectStatus'),error.message);return}$('#projectModal').hidden=true;await loadProjects();updateCounts()});
async function deleteProject(id){if(!confirm('Delete this project and its photo records?'))return;const {error}=await db.from('projects').delete().eq('id',id);if(error){alert(error.message);return}await refreshAll()}
async function togglePublish(id){const p=state.projects.find(x=>x.id===id);if(!p)return;const {error}=await db.from('projects').update({published:!p.published,updated_at:new Date().toISOString()}).eq('id',id);if(error){alert(error.message);return}await loadProjects()}
async function loadServices(){const {data,error}=await db.from('services').select('*').order('sort_order');if(error)return;state.services=data||[];const el=$('#serviceList');el.innerHTML=state.services.map(s=>`<div class="service-edit" data-service="${s.id}"><span>${String(s.sort_order).padStart(2,'0')}</span><div><input class="svc-name" value="${escAttr(s.name)}"><textarea class="svc-desc">${esc(s.description||'')}</textarea></div><input class="svc-price" value="${escAttr(s.price||'')}" placeholder="Price"><label class="svc-active"><input class="svc-on" type="checkbox" ${s.active?'checked':''}> LIVE</label><button class="primary save-service">SAVE</button><button class="danger delete-service">DELETE</button></div>`).join('');$$('.save-service').forEach(b=>b.onclick=()=>saveService(b.closest('.service-edit')));$$('.delete-service').forEach(b=>b.onclick=()=>deleteService(b.closest('.service-edit').dataset.service))}
$('#newServiceBtn').onclick=async()=>{const {error}=await db.from('services').insert({name:'NEW SERVICE',description:'',price:'',sort_order:state.services.length+1,active:true});if(error)alert(error.message);else await loadServices()};async function saveService(row){const id=row.dataset.service;const {error}=await db.from('services').update({name:row.querySelector('.svc-name').value.trim(),description:row.querySelector('.svc-desc').value.trim(),price:row.querySelector('.svc-price').value.trim(),active:row.querySelector('.svc-on').checked,updated_at:new Date().toISOString()}).eq('id',id);if(error)alert(error.message)}async function deleteService(id){if(!confirm('Delete service?'))return;const {error}=await db.from('services').delete().eq('id',id);if(error)alert(error.message);else await loadServices()}
$('#uploadBtn').onclick=async()=>{const projectId=$('#photoProject').value,files=[...$('#photoFiles').files];if(!projectId){msg($('#uploadStatus'),'Selecciona un proyecto.');return}if(!files.length){msg($('#uploadStatus'),'Selecciona fotografías.');return}msg($('#uploadStatus'),`Subiendo ${files.length} fotos…`);let ok=0;for(let i=0;i<files.length;i++){const f=files[i];if(!f.type.startsWith('image/'))continue;const ext=(f.name.split('.').pop()||'jpg').toLowerCase();const path=`projects/${projectId}/${Date.now()}-${crypto.randomUUID()}.${ext}`;const {error:up}=await db.storage.from('paquito-photos').upload(path,f,{cacheControl:'31536000',upsert:false});if(up){console.error(up);continue}const {data:urlData}=db.storage.from('paquito-photos').getPublicUrl(path);const {error:ins}=await db.from('photos').insert({project_id:projectId,storage_path:path,public_url:urlData.publicUrl,caption:f.name,sort_order:i});if(!ins)ok++;if(i===0){await db.from('projects').update({cover_url:urlData.publicUrl,updated_at:new Date().toISOString()}).eq('id',projectId)}}msg($('#uploadStatus'),`${ok} de ${files.length} fotos subidas.`,true);$('#photoFiles').value='';await loadProjects();await loadPhotoCount()};
async function loadRequests(){const {data,error}=await db.from('requests').select('*').order('created_at',{ascending:false});const el=$('#requestList');if(error){el.innerHTML=`<div class="empty-table"><p>${esc(error.message)}</p></div>`;return}if(!data?.length){el.innerHTML='<div class="empty-table"><div class="empty-icon">00</div><h3>NO REQUESTS</h3><p>Aquí aparecerán los contactos de la web.</p></div>';return}el.innerHTML=data.map(r=>`<div class="request-row"><div><small>${new Date(r.created_at).toLocaleString()}</small><strong>${esc(r.name)} · ${esc(r.email)}</strong><span>${esc(r.organization||'')} · ${esc(r.project_type||'')}</span><p>${esc(r.message||'')}</p></div><select data-request-status="${r.id}"><option ${r.status==='new'?'selected':''}>new</option><option ${r.status==='contacted'?'selected':''}>contacted</option><option ${r.status==='closed'?'selected':''}>closed</option></select></div>`).join('');$$('[data-request-status]').forEach(s=>s.onchange=async()=>{const {error}=await db.from('requests').update({status:s.value}).eq('id',s.dataset.requestStatus);if(error)alert(error.message)});$('#countRequests').textContent=data.length}
$('#saveProfile').onclick=()=>msg($('#profileStatus'),'El perfil visual se mantiene en el frontend por ahora. La información de proyectos, servicios y solicitudes ya es dinámica.',true);
function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}function escAttr(v){return esc(v)}
boot();