(()=>{const reduce=window.matchMedia?.('(prefers-reduced-motion: reduce)').matches;
const loader=document.createElement('div');loader.className='pf-loader';loader.innerHTML='<div class="pf-loader-mark">PF<span style="color:#08090a">.</span></div><div class="pf-loader-line"></div>';document.body.prepend(loader);
const transition=document.createElement('div');transition.className='pf-page-transition';document.body.appendChild(transition);
const progress=document.createElement('div');progress.className='pf-scroll-progress';document.body.appendChild(progress);
if(!reduce){const cursor=document.createElement('div');cursor.className='pf-cursor';const dot=document.createElement('div');dot.className='pf-cursor-dot';document.body.append(cursor,dot);let x=innerWidth/2,y=innerHeight/2,tx=x,ty=y;addEventListener('pointermove',e=>{tx=e.clientX;ty=e.clientY;cursor.classList.add('is-visible');dot.classList.add('is-visible')},{passive:true});const tick=()=>{x+=(tx-x)*.18;y+=(ty-y)*.18;cursor.style.transform=`translate(${x}px,${y}px) translate(-50%,-50%)`;dot.style.transform=`translate(${tx}px,${ty}px) translate(-50%,-50%)`;requestAnimationFrame(tick)};tick();document.querySelectorAll('a,button,.work-card,.project,.filter').forEach(el=>{el.addEventListener('mouseenter',()=>cursor.classList.add('is-hover'));el.addEventListener('mouseleave',()=>cursor.classList.remove('is-hover'))})}
requestAnimationFrame(()=>{document.body.classList.add('pf-ready');setTimeout(()=>loader.classList.add('is-done'),650)});
const updateProgress=()=>{const h=document.documentElement.scrollHeight-innerHeight;progress.style.width=(h>0?(scrollY/h)*100:0)+'%'};addEventListener('scroll',updateProgress,{passive:true});updateProgress();
if(!reduce){const hero=document.querySelector('.hero'),heroImage=document.querySelector('.hero-image');addEventListener('scroll',()=>{if(!hero||!heroImage)return;const r=hero.getBoundingClientRect();if(r.bottom>0&&r.top<innerHeight){const p=Math.max(0,Math.min(1,-r.top/Math.max(1,r.height-innerHeight)));heroImage.style.transform=`scale(1.07) translate3d(0,${p*7}%,0)`}}, {passive:true})}
const internal=a=>{const href=a.getAttribute('href');return href&&href.startsWith(location.origin)&&!href.includes('#')&&!a.target&&href.split('?')[0]!==location.href.split('?')[0]};document.querySelectorAll('a').forEach(a=>{if(internal(a)&&!reduce)a.addEventListener('click',e=>{e.preventDefault();const href=a.href;document.body.classList.add('pf-page-leaving');transition.classList.add('is-active');setTimeout(()=>location.href=href,560)})});
addEventListener('pageshow',()=>{document.body.classList.remove('pf-page-leaving');transition.classList.remove('is-active');setTimeout(()=>document.body.classList.add('pf-page-entering'),40);setTimeout(()=>document.body.classList.remove('pf-page-entering'),700)});
const obs=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');obs.unobserve(e.target)}}),{threshold:.12,rootMargin:'0px 0px -8% 0px'});document.querySelectorAll('.section-heading,.work-card,.service-row,.about-copy,.contact-inner,.project,.portfolio-head,.filters').forEach((el,i)=>{if(!el.classList.contains('reveal'))el.classList.add('reveal');el.style.transitionDelay=`${Math.min(i%5,4)*70}ms`;obs.observe(el)});
})();
