const db=window.PF_SUPABASE;
const grid=document.getElementById('projectGrid'),lightbox=document.getElementById('lightbox'),close=document.getElementById('closeLightbox'),visual=document.getElementById('lightboxVisual'),titleEl=document.getElementById('lightboxTitle'),metaEl=document.getElementById('lightboxMeta'),galleryEl=document.getElementById('lightboxGallery');
const categoryNames={boxes:'BOXES',box:'BOXES',training:'ENTRENAMIENTO',competition:'COMPETICIÓN',athletes:'ATLETAS',events:'EVENTOS',event:'EVENTOS',other:'OTROS'};
const translateCategory=v=>categoryNames[String(v??'').trim().toLowerCase()]||String(v||'PROYECTO').toUpperCase();
const demo=[['training','EL DÍA A DÍA','Entrenamiento · Gibraltar · 2026','tone-a'],['athletes','SIN REPETICIONES FÁCILES','Atletas · Gibraltar · 2026','tone-b'],['boxes','HECHO EN COMUNIDAD','Boxes · Gibraltar · 2026','tone-c'],['competition','CUANDO IMPORTA','Competición · Gibraltar · 2026','tone-d']];
let cards=[];
function esc(v){return String(v??'').replace(/[&<>\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[m]))}function escAttr(v){return esc(v).replace(/'/g,'%27')}
function renderDemo(){grid.innerHTML=demo.map((x,i)=>`<article class="project ${i===0?'project-large':''}" data-category="${x[0]}" data-title="${x[1]}" data-meta="${x[2]}"><div class="project-image ${x[3]}"><span>${String(i+1).padStart(2,'0')}</span></div><div class="project-meta"><span>${translateCategory(x[0])}</span><strong>${x[1]}</strong></div></article>`).join('');cards=[...grid.querySelectorAll('.project')];cards.forEach(c=>c.addEventListener('click',()=>openCard(c,[])));}
async function loadProjects(){if(!db){renderDemo();return}try{const {data,error}=await db.from('projects').select('id,name,category,location,event_date,description,cover_url').eq('published',true).order('created_at',{ascending:false});if(error)throw error; if(!data?.length){renderDemo();return}
const ids=data.map(p=>p.id);let photos=[];if(ids.length){const r=await db.from('photos').select('project_id,public_url,caption,sort_order').in('project_id',ids).order('sort_order',{ascending:true});if(!r.error)photos=r.data||[]}
const firstPhoto=new Map();photos.forEach(ph=>{if(ph.public_url&&!firstPhoto.has(ph.project_id))firstPhoto.set(ph.project_id,ph.public_url)});
grid.innerHTML=data.map((p,i)=>{const cover=p.cover_url||firstPhoto.get(p.id)||'';return `<article class="project ${i===0?'project-large':''}" data-id="${escAttr(p.id)}" data-category="${escAttr((p.category||'other').toLowerCase())}" data-title="${escAttr(p.name)}" data-meta="${escAttr([translateCategory(p.category),p.location,p.event_date].filter(Boolean).join(' · '))}"><div class="project-image ${cover?'has-cover':''}">${cover?`<img src="${escAttr(cover)}" alt="${escAttr(p.name)}" loading="lazy">`:''}<span>${String(i+1).padStart(2,'0')}</span></div><div class="project-meta"><span>${translateCategory(p.category)}</span><strong>${esc(p.name)}</strong></div></article>`}).join('');
cards=[...grid.querySelectorAll('.project')];cards.forEach(c=>c.addEventListener('click',()=>openCard(c,photos.filter(p=>p.project_id===c.dataset.id))));const hash=location.hash.slice(1);if(hash){const c=cards.find(x=>x.dataset.id===hash);if(c)c.click()}}catch(e){console.warn('No se pudo cargar el portfolio:',e);renderDemo()}}
function openCard(card,photos){titleEl.textContent=card.dataset.title||'PROYECTO';metaEl.textContent=card.dataset.meta||'';galleryEl.innerHTML='';visual.innerHTML='';visual.className='lightbox-visual';const source=card.querySelector('.project-image img');if(source){const img=document.createElement('img');img.src=source.src;img.alt=card.dataset.title||'Proyecto';img.className='lightbox-main-image';visual.appendChild(img)}else{const tone=card.querySelector('.project-image')?.className.split(' ').find(x=>x.startsWith('tone-'));if(tone)visual.classList.add(tone)}
photos.forEach((p,i)=>{if(!p.public_url)return;const img=document.createElement('img');img.src=p.public_url;img.alt=p.caption||`${card.dataset.title||'Proyecto'} — foto ${i+1}`;img.loading='lazy';galleryEl.appendChild(img)});if(!photos.length&&source){const img=document.createElement('img');img.src=source.src;img.alt=card.dataset.title||'Proyecto';galleryEl.appendChild(img)}lightbox.classList.add('open');lightbox.setAttribute('aria-hidden','false');document.body.style.overflow='hidden';}
function closeProject(){lightbox.classList.remove('open');lightbox.setAttribute('aria-hidden','true');document.body.style.overflow=''}close?.addEventListener('click',closeProject);lightbox?.addEventListener('click',e=>{if(e.target===lightbox)closeProject()});document.addEventListener('keydown',e=>{if(e.key==='Escape')closeProject()});document.querySelectorAll('.filter').forEach(f=>f.addEventListener('click',()=>{document.querySelectorAll('.filter').forEach(x=>x.classList.remove('active'));f.classList.add('active');const v=f.dataset.filter;cards.forEach(c=>c.style.display=v==='all'||c.dataset.category===v?'':'none')}));loadProjects();
